### ISSUE TITLE
Support for Authentication by Environment Variable

### ISSUE THREAD

**Issue by tohch4** [halprin/fcli#11]
We had discussed this outside of Github, are you still interested in this?

Currently, you can authenticate with a `--username` parameter and typing in the password interactively or via pipe.  However, it might be more conducive for password managers to allow the use of environment variables so a user can use something like `JIRA_USER` and `JIRA_PASS` so you do not need to enter passwords or do weird piping with additional parameters.

I will start a branch and work on a PR if you are interested.

**Comment by halprin** [comment]
Yes, a PR sounds awesome.  Notice I have a separate file for each authentication type.  Also, please add it to `combo.py` just like the other authentication types.
