### ISSUE TITLE
Username/password authentication is forgotten between ReST requests

### ISSUE THREAD

**Issue by halprin** [halprin/fcli#16]
A user must reenter his or her credentials for every ReST request if they choose to provide credentials via keyboard.  Have the credentials saved in memory between the requests so the user does not need to repeatedly enter the credentials.

**Comment by tohch4** [comment]
I thought this was the appeal of env vars in #14, no?

**Comment by halprin** [comment]
First, this story is about caching the credentials throughout _one_ execution of the CLI, not across multiple invocations.  Just want to make sure we are on the same page.

In any case, there may be a legitimate reason for someone who wants to stick to the keyboard exclusively, and I don't wish on them having to repeatedly enter their credentials throughout the single execution of the CLI.

**Comment by tohch4** [comment]
Yeah, duh, my bad. I guess this would be a hacky way to achieve that without memoization and real work. :-)  But I understand.
