### ISSUE TITLE
Add CLI Parameters to Set Importance, LOE, and Due Date Fields

### ISSUE THREAD

**Issue by tohch4** [halprin/fcli#25]
Now that QPPFC is moving towards specifying Importance, LOE (Level of Effort), and Due Date to all triage tickets, we should likely add these as parameters as a user can hand off and add to the bottom of the description to avoid the need to do manual edits in the browser after the fact.

I would like to work on this if you think it is a useful addition.

**Comment by sfradkin** [comment]
These will end up being added as custom fields to the triage type in jira if the team feels that using these to help prioritize is working out.

**Comment by sfradkin** [comment]
@tohch4 I can take this since I just wrote the scoring algorithm for the triage tasks, or we can work on it together.

**Comment by tohch4** [comment]
Sounds good I saw your PRs this morning.
