### ISSUE TITLE
add comment to ticket.

### ISSUE THREAD

**Issue by kungfulinux** [halprin/fcli#51]
Given a ticket number and a comment, add said comment to ticket.

**Comment by tohch4** [comment]
I'd like to take a whack at this. @halprin do we make a separate subcommand `fcli comment QPPFC-36 "This an updated comment` and take a triage ticket/task EL ticket/story ID or extend out on a subcommand like `fcli triage comment QPPFC-36`?

**Comment by halprin** [comment]
@tohch4, I like the first idea so you don't need to know or care what type of Jira entity it is.
